### ISSUE TITLE
Error when running (maybe I have to put in a different loaction?)

### ISSUE THREAD

**Issue by ghyujkilop** [tr4wzified/KnowYourEnemyPatcher#19]
System.ArgumentNullException: Value cannot be null.
   at Wabbajack.Common.GameMetaData.GameLocation()
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.GetDefaultRun(GameRelease release, ModKey targetModKey)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(String[] args, RunPreferences preferences)
Error occurred.  Press enter to exit

MY installation folder of skyrim is ina different spot. Any ideas on how to resolve?

**Comment by tr4wzified** [comment]
Make sure you have a valid Steam installation, you can always reinstall the game - should always do the trick. I think you should also be able to override it in the Synthesis settings? Not sure about that.

**Comment by ghyujkilop** [comment]
Oh, it's definitely a valid version. But yeah, I didn't want steam to
affect me running SKSE, so that's why I gave it its own folder and also
other models have suggested disassociating the Skyrim directory from
anything to do with steam. Is there a way to direct the app to the install
directory?

**Comment by tr4wzified** [comment]
If you open Synthesis and you click Skyrim Special Edition at the top you can manually enter the Data Folder Location there.
![image](https://user-images.githubusercontent.com/55751269/124467040-9be1d180-dd97-11eb-8f53-7ec68587f3a8.png)

**Comment by tr4wzified** [comment]
Closing due to inactivity & not an issue with the patcher
