### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by Glanzer-modder** [tr4wzified/KnowYourEnemyPatcher#23]
This is the same issue that was reported in issue #20 but it's still happening to me after updating to the latest version. I have verified that line 186 in my local copy of Program.cs was changed to "set" (instead of "add"). If I move KnowYourEnemyPatcher to the first in the Synthesis list, the problem goes away.

Here is the error (same as before on exact same item):

System.ArgumentException: An item with the same key has already been added. Key: 0F2595:Skyrim.esm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Noggog.Cache`2.Add(TObject item) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\Cache.cs:line 113
   at KnowYourEnemyMutagen.Program.RunPatch(IPatcherState`2 state) in C:\Users\Glanzer\AppData\Local\Temp\Synthesis\ae5a4sfy.5ne\Git\3bi0unqc.trp\Runner\KnowYourEnemyMutagen\Program.cs:line 158
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

Looking at the output, I do notice that it says "Add" instead of "Set" for the offending line. The item in question is a SPELL so shouldn't line 149 in the Program.cs also be changed to "Set"?

if (spellModified) state.PatchMod.Spells.Add(modifiedSpell);

**Comment by Glanzer-modder** [comment]
As an experiment I manually changed that line to the following and I no longer get the error:

if (spellModified) state.PatchMod.Spells.**Set**(modifiedSpell);

**Comment by Noggog** [comment]
Hey!  Good catch.  I'd agree with your changes.

I can either set up a PR for trawz to merge a bit later, or you can if you want to get listed as a contributor.  8)

**Comment by Glanzer-modder** [comment]
If you could do that it would be great. Thanks!

**Comment by tr4wzified** [comment]
Fixed, thank you. I had the habit of using Add instead of Set in earlier patchers
