### ISSUE TITLE
Vigilant Error

### ISSUE THREAD

**Issue by Nimick2002** [tr4wzified/KnowYourEnemyPatcher#29]
Hey, hoping you can help. Been getting this error when running the patcher:

Compiling
No extra data to consider
("C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\39b6eed6-a8c4-41b5-b1ce-66bcf123a2d7\Runner\DisplaySpellTomeLevelPatcher"): "dotnet" "build \"DisplaySpellTomeLevelPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "9fa09c761009aeb454144ea875a529d61b069655"
Running
(""): "dotnet" "run --project \"C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\39b6eed6-a8c4-41b5-b1ce-66bcf123a2d7\Runner\DisplaySpellTomeLevelPatcher\DisplaySpellTomeLevelPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"D:\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"D:\Modding\Tools\Synthesis\Data\Skyrim Special Edition\DisplaySpellTomeLevelPatcher\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\1 - DisplaySpellTomeLevelPatcher\Synthesis.esp\" --PatcherName DisplaySpellTomeLevelPatcher --SourcePath \"C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\1 - AOSISCSoundPatcher\Synthesis.esp\""
Mutagen version: 0.29.1
Mutagen sha: 96027a70ef8714620504a0c1c65a9d38ab342999
Synthesis version: 0.18.1
Synthesis sha: 2a6a42434dbfda2dbadbb08e8ce02403a4fedefd
run-patcher --DataFolderPath "D:\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "D:\Modding\Tools\Synthesis\Data\Skyrim Special Edition\DisplaySpellTomeLevelPatcher" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\Plugins.txt --OutputPath "C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\1 - DisplaySpellTomeLevelPatcher\Synthesis.esp" --PatcherName DisplaySpellTomeLevelPatcher --SourcePath "C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Workspace\Synthesis\1 - AOSISCSoundPatcher\Synthesis.esp"
Prepping state.
RecordException  => zzzCHSpiderStingPerk (0CFCB7:Vigilant.esm<Perk>): PerkEntryPointModifyValue did not have expected parameter type flag: 5 System.ArgumentException: PerkEntryPointModifyValue did not have expected parameter type flag: 5
   at Mutagen.Bethesda.Skyrim.Internals.PerkBinaryCreateTranslation.ParseEffects(IMutagenReadStream stream)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mutagen.Bethesda.Skyrim.Internals.PerkBinaryOverlay.EffectsCustomParse(OverlayStream stream, Int64 finalPos, Int32 offset, RecordType type, Nullable`1 lastParsed)
   at Mutagen.Bethesda.Skyrim.Internals.PerkBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, Nullable`1 lastParsed, Dictionary`2 recordParseCount, RecordTypeConverter recordTypeConverter)
   at Mutagen.Bethesda.Binary.BinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, RecordTypeConverter recordTypeConverter, RecordTypeFillWrapper fill)
   at Mutagen.Bethesda.Binary.BinaryOverlay.FillSubrecordTypes(IMajorRecordCommonGetter majorReference, OverlayStream stream, Int32 finalPos, Int32 offset, RecordTypeConverter recordTypeConverter, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Internals.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.EnumerateMajorRecordContexts(ISkyrimModGetter obj, ILinkCache linkCache, Type type, Boolean throwIfUnknown)+MoveNext()
   at Mutagen.Bethesda.ImmutableLoadOrderLinkCacheContextCategory`3.<TryResolveContext>g__AddRecords|6_0(TModGetter mod, Type type, <>c__DisplayClass6_0& )
   at Mutagen.Bethesda.ImmutableLoadOrderLinkCacheContextCategory`3.TryResolveContext(K key, Nullable`1 modKey, Type type, IModContext`4& majorRec)
   at Mutagen.Bethesda.MutableLoadOrderLinkCache`2.TryResolveContext(FormKey formKey, Type type, IModContext`4& majorRec)
   at DisplaySpellTomeLevelPatcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\User\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\39b6eed6-a8c4-41b5-b1ce-66bcf123a2d7\Runner\DisplaySpellTomeLevelPatcher\Program.cs:line 100
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 88
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 448
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 397
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 372

**Comment by Noggog** [comment]
Can probably disregard.  The mod itself is either malformed, or Mutagen needs to be upgraded to handle MultiplyValues /w the value being a spell (which is sees as an error currently)
