### ISSUE TITLE
Too many masters

### ISSUE THREAD

**Issue by PlayerBosta** [tr4wzified/KnowYourEnemyPatcher#31]
As the title says, i'm getting an error that i don't know it's supposed to happen in synthesis, the same error occurs on know your armor patcher:

Mutagen.Bethesda.Plugins.Exceptions.TooManyMastersException: Know your enemy.esp has too many masters on masters list. 313 >= 254.
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceCollection.SetTo(IEnumerable`1 masters)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ParallelWriteParameters parallelParam, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, ParallelWriteParameters parallelParam, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem, ParallelWriteParameters parallelWriteParams)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 617
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 472
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 833
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 460
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 432

**Comment by Noggog** [comment]
https://github.com/Mutagen-Modding/Synthesis/discussions/300

**Comment by tr4wzified** [comment]
What Noggog said
